server:
  error:
    include-stacktrace: never
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pogbet_db?useSSL=false
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update