server:
  port: 8080

spring:
  datasource:
    url: jdbc:sqlserver://mysqlserverpogbet.database.windows.net:1433;database=pogbet;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: pogbet@mysqlserverpogbet
    password: banco-pb-1A
  jpa:
    show-sql: "true"
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.SQLServer2012Dialect





